
version: "3.7"
services:
  nginx:
    container_name: static-test-website-1
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./webserver/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./webserver/nginx/ssl.conf:/etc/nginx/sites-enabled/ssl.conf
      - ./site:/usr/share/nginx/html
      - ./webserver/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./webserver/certs:/etc/nginx/certs
